update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "AppleSystemStatus.xcodeproj")
    build_app(scheme: "AppleSystemStatus")
    upload_to_testflight
  end
end
