update_fastlane

default_platform(:ios)

platform :ios do
  lane :beta do
    increment_build_number(xcodeproj: "iSystemStatus.xcodeproj")
    build_app(scheme: "iSystemStatus")
    upload_to_testflight
  end
  lane :release do
    get_certificates
    get_provisioning_profile
    increment_build_number(xcodeproj: "iSystemStatus.xcodeproj")
    build_app(scheme: "iSystemStatus")
    upload_to_app_store
  end
end
